name: id_card_app
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0




flutter:


  uses-material-design: true


  assets:
    - images/IDcardpic.jpg
    - images/comsatslogo.jpeg

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Bold.ttf
        - asset: fonts/Inter-Regular.ttf
        
    - family: QuickSand
      fonts:
        - asset: fonts/Quicksand-Medium.ttf
 
